version: "3.0"

services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: knoogle-server
        restart: always
        volumes:
            - .:/app
        environment:
            - APP_NAME=knoogle-server
        ports:
            - "8000:8000"
        expose:
            - 8000
    

