# Use the Python3.7.6 container image
FROM python:3.7-alpine

# Set the working directory to /app
WORKDIR /app

# Set env variables used by the flask command
# ENV FLASK_APP run.py
ENV FLASK_RUN_HOST=0.0.0.0 \
    FLASK_RUN_PORT=8000

# Install gcc so Python packages can compile speedups
RUN apk add --no-cache gcc musl-dev linux-headers
#RUN apt-get update \
#&& apt-get install -y --no-install-recommends apt-utils \
#&& apt-get install gcc -y \
#&& apt-get clean

# Copy the current directory contents into the container at /app
COPY . /app

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the project
COPY . /app

# Run the command to start uWSGI
CMD ["uwsgi", "app.ini"]

# Run the command to start FLASK
CMD ["flask", "run"]
