# Generated by Django 2.2.1 on 2019-06-18 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontologies', to='profiles.Profile'),
        ),
    ]
