# Development Dockerfile

# Sets node version
FROM node:12-slim

# Set working directory
WORKDIR /knoogle-client

# Add `/knoogle-client/node_modules/.bin` to $PATH
ENV PATH /knoogle-client/node_modules/.bin:$PATH

# Install and cache app dependencies
COPY package.json /knoogle-client/package.json
RUN npm install
RUN npm install react-scripts@3.0.1 -g --silent

# Start app
CMD ["npm", "start"]
